- name: Install apache2 web server
  become: true
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
  - apache2
  - libapache2-mod-php
  - php-mysql
  - php-curl 
  - php-gd 
  - php-intl 
  - php-json 
  - php-mbstring 
  - php-mcrypt 
  - php-xml 
  - php-zip 
  - php-mcrypt
  - php-fpm
  - libapache2-mod-security2

- name: Restart webserver
  become: yes
  service: name=apache2 state=restarted

- name: Enable apache2 modules
  become: yes
  command: a2enmod rewrite actions alias proxy_fcgi security2

### Clean and start services

- name: Hide server Apache 2 signature for security purpose
  blockinfile:
    path: /etc/apache2/apache2.conf
    follow: yes
    block: |
      ServerTokens Prod
      ServerSignature Off 

- name: Remove default apache2 index.html file
  file:
    path: /var/www/html/index.html 
    state: absent

- name: Restart webserver
  become: yes
  service: name=apache2 state=restarted