- name: Download Vtiger
  get_url:
    url: https://sourceforge.net/projects/vtigercrm/files/vtiger%20CRM%207.0.1/Core%20Product/vtigercrm7.0.1.tar.gz
    dest: /var/www/html/vtigercrm.tar.gz
    mode: 0664
    owner: www-data
    group: www-data

- name: Unarchive VTiger and copy to Apache Server
  unarchive:
    src: /var/www/html/vtigercrm.tar.gz
    dest: /var/www/html/
    owner: www-data
    group: www-data
    copy: no

- name: Create VTiger database
  mysql_db: name={{ vtiger_db_name }} state=present

- name: Create VTiger database user
  mysql_user: name={{ vtiger_db_user }} password={{ vtiger_db_password }} priv={{ vtiger_db_name }}.*:ALL host='localhost' state=present

